# Setup
title:               Akhil Sankar
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://fuzzygreenblurs.github.io
baseurl:             ''
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Akhil Sankar
  url:               https://github.com/fuzzygreenblurs
  linkedin:          https://linkedin.com/akhilsankar

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
