# Setup
title: Akhil Sankar
description: 'Personal site of Akhil Sankar.'
url: https://fuzzygreenblurs.github.io
baseurl: ""
paginate: 1
permalink: pretty

# About/contact
author:
  name: Akhil Sankar
  url: https://github.com/fuzzygreenblurs
  linkedin: https://linkedin.com/akhilsankar

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Collections
collections:
  pages:
    output: true

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Navbar page list
nav:
  - title: Projects
    url: /projects

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# Custom vars
version: 2.0.0
